openapi: 3.0.0
info:
  version: 1.0.0
  title: Base Node App
  description: Skeleton application based on node technologies like Express, Vue.js, ...
  contact:
    name: Benoît Development
    email: benoit.development@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  servers:
    - url: http://localhost:3000
paths:
  /topics:
    get:
      description: Returns a list of topics
      operationId: topics
      tags:
        - Topics
      responses:
        '200':
          description: list of topics
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 1
                  topics:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          required: true
                          example: 42
                        name:
                          type: string
                          required: true
                        summary:
                          type: string
                        image:
                          type: string
                          format: uri
                