name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:

  build:
    env:
      api_folder: ./api

    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Echo api folder
        run: ls -R
        working-directory: ${{ env.api_folder }}
