name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:

  build:
    env:
      api-directory: ./api

    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: API folder listing
        run: ls -R
        working-directory: ${{ env.api-directory }}
      - name: Test API
        run: |
          npm install
          npm test
        working-directory: ${{ env.api-directory }}
