name: Node-BaseApp
on: [push]

jobs:

  build:
    env:
      api-directory: ./api
      app-directory: ./app

    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: API folder listing
        run: ls -R
        working-directory: ${{ env.api-directory }}
      - name: Test API
        run: |
          npm install
          npm test
          npm run lint
        working-directory: ${{ env.api-directory }}
      - name: APP folder listing
        run: ls -R
        working-directory: ${{ env.app-directory }}
      - name: Test APP
        run: |
          npm install
          npm run test
          npm run lint
        working-directory: ${{ env.app-directory }}
